version: "3.5"

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
    - .:/usr/client/src/app

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/
    ports:
      - "3000:3000"
    depends_on:
      - 'database'

  database:
    image: mongo:latest
    command: mongod --port 27015
    environment:
      - MONGODB_DATABASE="backend-chat"
    ports:
      - "27015:27015"